export default {
  name: 'content',
  type: 'array',
  title: 'Komponenty podstrony',
  of: [
    { type: 'HeroBackgroundImg' },
    { type: 'Benefits' },
    { type: 'Faq' },
    { type: 'Opinions' },
    { type: 'TileList' },
    { type: 'CtaSection' },
    { type: 'SimpleCtaSection' },
    { type: 'CourseModules' },
    { type: 'ImageShowcase' },
    { type: 'Bonuses' },
    { type: 'TilesGrid' },
    { type: 'TilesSticky' },
    { type: 'TilesFeatures' },
    { type: 'Community' },
    { type: 'Reviews' },
    { type: 'Introduction' },
    { type: 'ContactForm' },
    { type: 'TabSection' },
    { type: 'TilesIndicated' },
  ]
}